# Generated by Django 4.2.6 on 2023-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('Empo', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.IntegerField(max_length=20)),
                ('Mgr', models.IntegerField()),
                ('Hire', models.DateField()),
                ('Sal', models.IntegerField()),
                ('Comm', models.IntegerField()),
                ('Dept', models.IntegerField()),
            ],
        ),
    ]
