# Generated by Django 4.2.6 on 2023-12-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employeetable_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.IntegerField()),
                ('Loc', models.CharField(max_length=200)),
                ('Deptno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employeetable')),
            ],
        ),
    ]
