# Generated by Django 4.2.6 on 2023-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='D_name',
            field=models.CharField(max_length=50),
        ),
    ]
